### ISSUE TITLE
Outline view not useful: shows a node for every line

### ISSUE THREAD

**Issue by Psychlist1972** [appliedengdesign/vscode-gcode-syntax#6] opened 2020-01-11 00:44 UTC
I would have expected the move/cutting operations to be grouped. Is this the expected output?

![image](https://user-images.githubusercontent.com/1421146/72195686-9e04e300-33e1-11ea-8e10-3e5459a4f185.png)

**Comment by mikecentola** [comment] 2020-01-12 02:39
It bases the tree nodes on the G00/G01/G02/G03 commands. Since you have a G1 on each line, it's technically working as intended. You don't need a G1 on lines following. I could add some kind of logic to determine if it should suppress some of that but its doing a linear move each time.

**Comment by Psychlist1972** [comment] 2020-01-12 08:02
Thanks. Not my gcode; it's a sample file that came with an inexpensive 3018 CNC router.

I'm not sure if any other CAM programs generate code with the modal command on each line.

**Comment by mikecentola** [comment] 2020-01-12 13:52
> Thanks. Not my gcode; it's a sample file that came with an inexpensive 3018 CNC router.
> 
> I'm not sure if any other CAM programs generate code with the modal command on each line.

I know in the CAM program I use (RhinoCAM) the post processor has options to “optimize” code which will output the Modal and then just X Y or Z changes. 

I’ll close this for now. Thanks

**Closed by mikecentola** 2020-01-12 13:52 UTC
